kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx
  labels:
    name: nginx-deployment
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: nginx
     role: nginx
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.7
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.1
              memory: 128Mi
            requests:
              memory: 64Mi
              cpu: 0.05
    metadata:
      labels:
        name: nginx
        role: nginx
