kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: db
  labels:
    name: db-deployment
    app: voting-app
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
     name: db
     role: sqldb
     app: voting-app
  template:
    spec:
      containers:
        - name: db
          image: postgres:9.4
          resources:
            limits:
              memory: 256Mi
              cpu: 0.25
            requests:
              memory: 128Mi
    metadata:
      labels:
        name: db
        role: sqldb
        app: voting-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: db
  name: db
  namespace: voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: db
    app: voting-app
    role: sqldb
