kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: result
  labels:
    name: result-deployment
    app: voting-app
  namespace: voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
     name: result
     role: resultapp
     app: voting-app
  template:
    spec:
      containers:
        - name: result
          image: bencer/example-voting-app-result:metrics-3
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 32Mi
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
      labels:
        name: result
        role: resultapp
        app: voting-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: result
  name: result
  namespace: voting-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result
    app: voting-app
    role: resultapp
